server:
  port: 8088
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test-db;MODE=MYSQL
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace